obstacle_range: 1.5
raytrace_range: 3.5
robot_radius: 0.20
inflation_radius: 0.25
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
